In [ ]:
import pandas as pd

tested_out = ["FX_CWSI", "FX_RO"]
df = pd.DataFrame(
    [
        ["Bronze", "Floor", "pirouette", "P", 0, "P.0", "FX_P[180]", 0],
        ["Bronze", "Floor", "tumbling pass 1", "TP1", 0, "TP1.0", "FX_CWSI", 0],
        ["Bronze", "Floor", "tumbling pass 2", "TP2", 0, "TP2.0", "FX_HS", 0],
        ["Bronze", "Floor", "tumbling pass 2", "TP2", 2, "TP2.2", "FX_SA", 4],
        ["Bronze", "Floor", "dance series", "DS", 0, "DS.0", "FX_SPL[60]", 0],
        ["Bronze", "Floor", "tumbling pass 2", "TP2", 1, "TP2.1", "FX_BWO", 1],
        ["Bronze", "Floor", "tumbling pass 1", "TP1", 1, "TP1.1", "FX_RO", 2],
        ["Bronze", "Floor", "tumbling pass 1", "TP1", 2, "TP1.2", "FX_ROBHS", 3],
    ],
    columns=[
        "Level",
        "Event",
        "Routine Skill Category Description",
        "Routine Skill Category ID",
        "Skill Rank In Category",
        "Routine Skill ID",
        "Skill ID",
        "Default Upgrade Order",
    ],
)
df = df.sort_values(
    ["Level", "Event", "Routine Skill Category ID", "Skill Rank In Category"]
)


df["idx"] = df.apply(
    lambda row: (
        pd.NA if row["Skill ID"] in tested_out else row["Skill Rank In Category"]
    ),
    axis=1,
)
df["idx_min"] = df.groupby(["Level", "Event", "Routine Skill Category ID"])[
    "idx"
].transform("min")
df["idx_diff"] = df["idx"] - df["idx_min"]


def custom_upgrade_order(row):
    if not pd.isna(row["idx_diff"]) and row["idx_diff"] > 0:
        return row["Default Upgrade Order"]
    else:
        return row["idx_diff"]


df["Custom Upgrade Order"] = df.apply(custom_upgrade_order, axis=1)
df["Custom Upgrade Order"] = (
    df["Custom Upgrade Order"].rank(method="dense") - 1
).astype(pd.Int32Dtype())
df

,Level,Event,Routine Skill Category Description,Routine Skill Category ID,Skill Rank In Category,Routine Skill ID,Skill ID,Default Upgrade Order,idx,idx_min,idx_diff,Custom Upgrade Order
4,Bronze,Floor,dance series,DS,0,DS.0,FX_SPL[60],0,0,0,0,0
0,Bronze,Floor,pirouette,P,0,P.0,FX_P[180],0,0,0,0,0
1,Bronze,Floor,tumbling pass 1,TP1,0,TP1.0,FX_CWSI,0,<NA>,2,<NA>,<NA>
6,Bronze,Floor,tumbling pass 1,TP1,1,TP1.1,FX_RO,2,<NA>,2,<NA>,<NA>
7,Bronze,Floor,tumbling pass 1,TP1,2,TP1.2,FX_ROBHS,3,2,2,0,0
2,Bronze,Floor,tumbling pass 2,TP2,0,TP2.0,FX_HS,0,0,0,0,0
5,Bronze,Floor,tumbling pass 2,TP2,1,TP2.1,FX_BWO,1,1,0,1,1
3,Bronze,Floor,tumbling pass 2,TP2,2,TP2.2,FX_SA,4,2,0,2,2

In [ ]:
[0, 1, 2, 3, 4]
[None, 1, 2, None, 4]
[None, 0, 1, None, 2]

In [ ]:
pd.Series([None, 1, 2, None, 4]).rank() - 1

0    NaN
1    0.0
2    1.0
3    NaN
4    2.0
dtype: float64

In [139]:
import pandas as pd


scores = [9.0, 9.5, 9.4, 9.6]
meets = [f"Meet {i + 1}" for i in range(len(scores))]
df_competition_results = pd.DataFrame(
    {
        "Meet": meets,
        "Level": ["XS"] * len(scores),
        "Athlete": ["Evelyn"] * len(scores),
        "Beam": scores,
        # "Beam Routine": [1] * len(scores),
        "Beam Routine": [1] * (len(scores) - 1) + [2],
    }
)

df_skill_eval = pd.DataFrame(
    {
        "Period": [1] * 2,
        "Event": ["Beam"] * 2,
        "Athlete": ["Evelyn"] * 2,
        "Score": [3, 4],
        "Skill ID": ["J2", "D2"],
        "Level": ["XS"] * 2,
    }
)

default_routine_upgrades = {
    "XS": {
        "Beam": [("D1", "D2"), ("J1", "J2"), ("D2", "D3"), ("D3", "D4"), ("A1", "A2")]
    }
}
athlete_routine_baselines = {
    "XS": {
        "Beam": {
            "Evelyn": {"start_at": 1, "custom_upgrade_order": {"Beam": [0, 1, 2, 3, 4]}}
        }
    }
}
df_upgrade_tracker = pd.DataFrame(
    columns=[
        "Level",
        "Athlete",
        "Event",
        # "Active Round",
        "Upgrade Round",
        "Meet #1",
        "Score #1",
        "Meet #2",
        "Score #2",
        "Original skill",
        "New skill",
        "New skill score",
        "Upgrade in progress?",
        "Ready to upgrade?",
        "Is Active?",
        "Admin notes",  # added
    ]
)

In [ ]:
import numpy as np


EVENTS = ["Beam"]
_df_upgrade_tracker = df_upgrade_tracker.copy()
for i in [0, 1, 2, 3]:  # range(len(df_competition_results)):
    _level = df_competition_results.iloc[i]["Level"]
    _athlete = df_competition_results.iloc[i]["Athlete"]
    _meet = df_competition_results.iloc[i]["Meet"]

    for event in EVENTS:
        # _active_round = "?"
        _meet_1 = None
        _score_1 = None
        _meet_2 = None
        _score_2 = None
        _original_skill = None
        _new_skill = None
        _new_skill_score = None
        _active_round_index = None
        _upgrade_in_progress = None
        _ready_to_upgrade = None
        _close_current_round = None
        _admin_notes = None
        _event_score = df_competition_results.iloc[i][event]
        _upgrade_round = df_competition_results.iloc[i][f"{event} Routine"]
        _active_round_df = _df_upgrade_tracker[
            (_df_upgrade_tracker["Level"] == _level)
            & (_df_upgrade_tracker["Athlete"] == _athlete)
            & (_df_upgrade_tracker["Event"] == event)
            & (_df_upgrade_tracker["Is Active?"] == "TRUE")
        ]
        assert len(_active_round_df) <= 1, "Found multiple active rounds"
        if len(_active_round_df) == 0:
            _meet_1 = _meet
            _score_1 = _event_score
            # TODO: custom_upgrade_order
            _base_idx = athlete_routine_baselines[_level][event][_athlete]["start_at"]
            assert _base_idx == _upgrade_round, (
                f"unexpected skill index: {_base_idx=}, {_upgrade_round=}"
            )
            _original_skill, _new_skill = default_routine_upgrades[_level][event][
                _upgrade_round
            ]
        else:
            _active_round_s = _active_round_df.iloc[0]
            _active_round_index = int(_active_round_df.index[0])
            if _upgrade_round > _active_round_s["Upgrade Round"]:
                _close_current_round = True
                _admin_notes = "Routine competed was not ready for upgrade"
                # Same as above but without t0 validation
                _meet_1 = _meet
                _score_1 = _event_score
                # TODO: custom_upgrade_order
                _base_idx = athlete_routine_baselines[_level][event][_athlete][
                    "start_at"
                ]
                _original_skill, _new_skill = default_routine_upgrades[_level][event][
                    _upgrade_round
                ]
            elif _upgrade_round == _active_round_s["Upgrade Round"]:
                # TODO: just query the scores database?
                _original_skill = _active_round_s["Original skill"]
                _new_skill = _active_round_s["New skill"]

                _scores_history = [(_meet, _event_score)]
                if _active_round_s["Score #1"]:
                    _scores_history.append(
                        (_active_round_s["Meet #1"], _active_round_s["Score #1"])
                    )
                if _active_round_s["Score #2"]:
                    _scores_history.append(
                        (_active_round_s["Meet #2"], _active_round_s["Score #2"])
                    )
                _top_scores_history = sorted(
                    sorted(_scores_history, key=lambda x: x[1], reverse=True)[:2],
                    key=lambda x: x[0],
                )
                _meet_1 = _top_scores_history[0][0]
                _score_1 = _top_scores_history[0][1]
                if len(_top_scores_history) == 2:
                    _meet_2 = _top_scores_history[1][0]
                    _score_2 = _top_scores_history[1][1]
            else:
                # no-op
                (
                    _level,
                    _athlete,
                    _,
                    # _active_round,
                    _upgrade_round,
                    _meet_1,
                    _score_1,
                    _meet_2,
                    _score_2,
                    _original_skill,
                    _new_skill,
                    _new_skill_score,
                    _upgrade_in_progress,
                    _ready_to_upgrade,
                    _,
                    _admin_notes,
                ) = _active_round_s
        _new_skill_score = df_skill_eval[
            (df_skill_eval["Level"] == _level)
            & (df_skill_eval["Athlete"] == _athlete)
            & (df_skill_eval["Event"] == event)
            & (df_skill_eval["Skill ID"] == _new_skill)
        ]["Score"].max()
        # # for testing purposes
        # if i in (2, 3):
        #     _new_skill_score = 4
        _new_skill_score = None if pd.isna(_new_skill_score) else _new_skill_score

        if _score_1 is not None or _score_2 is not None or _new_skill_score is not None:
            _upgrade_in_progress = "TRUE"
        else:
            _upgrade_in_progress = "FALSE"

        if all([_score_1, _score_2]) and _score_1 >= 9.4 and _score_2 >= 9.4:
            if _new_skill_score >= 4:
                _ready_to_upgrade = "YES"
            elif _new_skill_score >= 3:
                _ready_to_upgrade = "MAYBE"
        else:
            _ready_to_upgrade = "NO"

        _data = [
            _level,
            _athlete,
            event,
            # _active_round,
            _upgrade_round,
            _meet_1,
            _score_1,
            _meet_2,
            _score_2,
            _original_skill,
            _new_skill,
            _new_skill_score,
            _upgrade_in_progress,
            _ready_to_upgrade,
            "TRUE",
            _admin_notes,
        ]
        if _close_current_round:
            print("here1")
            print(_active_round_index)
            print(_df_upgrade_tracker.loc[_active_round_index, "Is Active?"])
            _df_upgrade_tracker.loc[_active_round_index, "Is Active?"] = "FALSE"
            print(_df_upgrade_tracker.loc[_active_round_index, "Is Active?"])
            _active_round_index = None

        if _active_round_index is not None:
            print("here2")
            print(_active_round_index)
            # update
            _df_upgrade_tracker.loc[_active_round_index] = _data
        else:
            print("here3")
            # append
            _df_upgrade_tracker.loc[len(_df_upgrade_tracker)] = _data

here3
here2
0
here2
0
here1
0
TRUE
FALSE
here3

In [141]:
_df_upgrade_tracker

,Level,Athlete,Event,Upgrade Round,Meet #1,Score #1,Meet #2,Score #2,Original skill,New skill,New skill score,Upgrade in progress?,Ready to upgrade?,Is Active?,Admin notes
0,XS,Evelyn,Beam,1,Meet 2,9.5,Meet 3,9.4,J1,J2,3,TRUE,MAYBE,FALSE,None
1,XS,Evelyn,Beam,2,Meet 4,9.6,None,None,D2,D3,None,TRUE,NO,TRUE,Routine competed was not ready for upgrade

In [ ]:
# import pandas as pd


# scores = [9.0, 9.5, 9.4, 9.6]
# meets = [f"Meet {i+1}" for i in range(len(scores))]
# df_competition_results = pd.DataFrame(
#     {
#         "Meet": meets,
#         "Level": ["XS"] * len(scores),
#         "Athlete": ["Evelyn"] * len(scores),
#         "Beam": scores,
#         # "Beam Routine": [1] * len(scores),
#         "Beam Routine": [1] * (len(scores) - 1) + [2],
#     }
# )

# df_skill_eval = pd.DataFrame(
#     {
#         "Period": [1] * 2,
#         "Event": ["Beam"] * 2,
#         "Athlete": ["Evelyn"] * 2,
#         "Score": [3, 4],
#         "Skill ID": ["J2", "D2"],
#         "Level": ["XS"] * 2,
#     }
# )

# default_routine_upgrades = {
#     "XS": {
#         "Beam": [("D1", "D2"), ("J1", "J2"), ("D2", "D3"), ("D3", "D4"), ("A1", "A2")]
#     }
# }
# athlete_routine_baselines = {
#     "XS": {
#         "Beam": {
#             "Evelyn": {"start_at": 1, "custom_upgrade_order": {"Beam": [0, 1, 2, 3, 4]}}
#         }
#     }
# }
# df_upgrade_tracker = pd.DataFrame(
#     columns=[
#         "Level",
#         "Athlete",
#         "Event",
#         # "Active Round",
#         "Upgrade Round",
#         "Meet #1",
#         "Score #1",
#         "Meet #2",
#         "Score #2",
#         "Original skill",
#         "New skill",
#         "New skill score",
#         "Upgrade in progress?",
#         "Ready to upgrade?",
#         "Is Active?",
#         "Admin notes",  # added
#     ]
# )

# Refactor

In [222]:
scores = [9.0, 9.5, 9.4, 9.6]
meets = [f"Meet {i + 1}" for i in range(len(scores))]
df_competition_results = pd.DataFrame(
    {
        "Meet": meets,
        "Level": ["XB"] * len(scores),
        "Athlete": ["Autumn"] * len(scores),
        "Beam": scores,
        "Beam Routine": [1] * (len(scores) - 1) + [2],
    }
)

In [223]:
df_competition_results["Bars"] = [9.0, 9.5, 9.4, 9.6]
df_competition_results["Bars Routine"] = [1, 1, 1, 1]
df_competition_results.loc[len(df_competition_results)] = [
    "Meet 1",
    "XS",
    "Kristy",
    8.5,
    0,
    8.5,
    0,
]

In [224]:
scores_long = pd.melt(
    df_competition_results,
    id_vars=["Meet", "Level", "Athlete"],
    value_vars=["Beam", "Bars"],
    var_name="Event",
    value_name="Event Score",
)
scores_long

     Meet Level Athlete Event  Event Score
0  Meet 1    XB  Autumn  Beam          9.0
1  Meet 2    XB  Autumn  Beam          9.5
2  Meet 3    XB  Autumn  Beam          9.4
3  Meet 4    XB  Autumn  Beam          9.6
4  Meet 1    XS  Kristy  Beam          8.5
5  Meet 1    XB  Autumn  Bars          9.0
6  Meet 2    XB  Autumn  Bars          9.5
7  Meet 3    XB  Autumn  Bars          9.4
8  Meet 4    XB  Autumn  Bars          9.6
9  Meet 1    XS  Kristy  Bars          8.5

In [225]:
routine_long = pd.melt(
    df_competition_results,
    id_vars=["Meet", "Level", "Athlete"],
    value_vars=["Beam Routine", "Bars Routine"],
    var_name="Event",
    value_name="Event Routine",
)
routine_long["Event"] = routine_long["Event"].apply(lambda x: x.split(" ")[0])
routine_long

     Meet Level Athlete Event  Event Routine
0  Meet 1    XB  Autumn  Beam              1
1  Meet 2    XB  Autumn  Beam              1
2  Meet 3    XB  Autumn  Beam              1
3  Meet 4    XB  Autumn  Beam              2
4  Meet 1    XS  Kristy  Beam              0
5  Meet 1    XB  Autumn  Bars              1
6  Meet 2    XB  Autumn  Bars              1
7  Meet 3    XB  Autumn  Bars              1
8  Meet 4    XB  Autumn  Bars              1
9  Meet 1    XS  Kristy  Bars              0

In [226]:
routine_scores_long = pd.merge(
    scores_long, routine_long, on=["Meet", "Level", "Athlete", "Event"], how="inner"
)
routine_scores_long

     Meet Level Athlete Event  Event Score  Event Routine
0  Meet 1    XB  Autumn  Beam          9.0              1
1  Meet 2    XB  Autumn  Beam          9.5              1
2  Meet 3    XB  Autumn  Beam          9.4              1
3  Meet 4    XB  Autumn  Beam          9.6              2
4  Meet 1    XS  Kristy  Beam          8.5              0
5  Meet 1    XB  Autumn  Bars          9.0              1
6  Meet 2    XB  Autumn  Bars          9.5              1
7  Meet 3    XB  Autumn  Bars          9.4              1
8  Meet 4    XB  Autumn  Bars          9.6              1
9  Meet 1    XS  Kristy  Bars          8.5              0

In [242]:
xs_bb_ug = [("D1", "D2"), ("A1", "A2")]
xs_ub_ug = [("D1", "D2"), ("C1", "C2")]
xb_bb_ug = [("D1", "D2"), ("J1", "J2"), ("D2", "D3"), ("D3", "D4"), ("A1", "A2")]
xb_ub_ug = [("D1", "D2"), ("D2", "D3")]

routine_upgrades_df = pd.DataFrame(
    {
        "Level": ["XS"] * len(xs_bb_ug + xs_ub_ug) + ["XB"] * len(xb_bb_ug + xb_ub_ug),
        "Event": ["Beam"] * len(xs_bb_ug)
        + ["Bars"] * len(xs_ub_ug)
        + ["Beam"] * len(xb_bb_ug)
        + ["Bars"] * len(xb_ub_ug),
        "Event Routine": list(range(len(xs_bb_ug)))
        + list(range(len(xs_ub_ug)))
        + list(range(len(xb_bb_ug)))
        + list(range(len(xb_ub_ug))),
        "Skill to Upgrade": [i for i, _ in xs_bb_ug]
        + [i for i, _ in xs_ub_ug]
        + [i for i, _ in xb_bb_ug]
        + [i for i, _ in xb_ub_ug],
        "Upgrade Skill": [j for _, j in xs_bb_ug]
        + [j for _, j in xs_ub_ug]
        + [j for _, j in xb_bb_ug]
        + [j for _, j in xb_ub_ug],
    }
)
routine_upgrades_df.sort_values(["Level", "Event", "Event Routine"])

   Level Event  Event Routine Skill to Upgrade Upgrade Skill
9     XB  Bars              0               D1            D2
10    XB  Bars              1               D2            D3
4     XB  Beam              0               D1            D2
5     XB  Beam              1               J1            J2
6     XB  Beam              2               D2            D3
7     XB  Beam              3               D3            D4
8     XB  Beam              4               A1            A2
2     XS  Bars              0               D1            D2
3     XS  Bars              1               C1            C2
0     XS  Beam              0               D1            D2
1     XS  Beam              1               A1            A2

In [243]:
athlete_df = routine_scores_long[["Level", "Athlete"]].drop_duplicates()
athlete_df

  Level Athlete
0    XB  Autumn
4    XS  Kristy

In [244]:
xs_athlete_routine_cross = pd.merge(
    athlete_df[athlete_df["Level"] == "XS"][["Athlete"]],
    routine_upgrades_df[routine_upgrades_df["Level"] == "XS"],
    how="cross",
)
xs_athlete_routine_cross

  Athlete Level Event  Event Routine Skill to Upgrade Upgrade Skill
0  Kristy    XS  Beam              0               D1            D2
1  Kristy    XS  Beam              1               A1            A2
2  Kristy    XS  Bars              0               D1            D2
3  Kristy    XS  Bars              1               C1            C2

In [245]:
xb_athlete_routine_cross = pd.merge(
    athlete_df[athlete_df["Level"] == "XB"][["Athlete"]],
    routine_upgrades_df[routine_upgrades_df["Level"] == "XB"],
    how="cross",
)
xb_athlete_routine_cross

  Athlete Level Event  Event Routine Skill to Upgrade Upgrade Skill
0  Autumn    XB  Beam              0               D1            D2
1  Autumn    XB  Beam              1               J1            J2
2  Autumn    XB  Beam              2               D2            D3
3  Autumn    XB  Beam              3               D3            D4
4  Autumn    XB  Beam              4               A1            A2
5  Autumn    XB  Bars              0               D1            D2
6  Autumn    XB  Bars              1               D2            D3

In [246]:
athlete_routine_cross = pd.concat(
    [xs_athlete_routine_cross, xb_athlete_routine_cross], axis=0
)
athlete_routine_cross["Custom Skill to Upgrade"] = None
athlete_routine_cross["Custom Upgrade Skill"] = None
athlete_routine_cross = athlete_routine_cross.rename(
    columns={
        "Skill to Upgrade": "Default Skill to Upgrade",
        "Upgrade Skill": "Default Upgrade Skill",
    }
)
athlete_routine_cross

,Athlete,Level,Event,Event Routine,Default Skill to Upgrade,Default Upgrade Skill,Custom Skill to Upgrade,Custom Upgrade Skill
0,Kristy,XS,Beam,0,D1,D2,None,None
1,Kristy,XS,Beam,1,A1,A2,None,None
2,Kristy,XS,Bars,0,D1,D2,None,None
3,Kristy,XS,Bars,1,C1,C2,None,None
0,Autumn,XB,Beam,0,D1,D2,None,None
1,Autumn,XB,Beam,1,J1,J2,None,None
2,Autumn,XB,Beam,2,D2,D3,None,None
3,Autumn,XB,Beam,3,D3,D4,None,None
4,Autumn,XB,Beam,4,A1,A2,None,None
5,Autumn,XB,Bars,0,D1,D2,None,None
6,Autumn,XB,Bars,1,D2,D3,None,None

In [247]:
custom_routine_sequence = {"Kristy": {"Bars": {0: ("D2", "D1")}}}
for athlete, events in custom_routine_sequence.items():
    for event, updates in events.items():
        for routine_id, (from_skill, to_skill) in updates.items():
            athlete_routine_cross.loc[
                (athlete_routine_cross["Athlete"] == athlete)
                & (athlete_routine_cross["Event"] == event)
                & (athlete_routine_cross["Event Routine"] == routine_id),
                "Custom Skill to Upgrade",
            ] = from_skill
            athlete_routine_cross.loc[
                (athlete_routine_cross["Athlete"] == athlete)
                & (athlete_routine_cross["Event"] == event)
                & (athlete_routine_cross["Event Routine"] == routine_id),
                "Custom Upgrade Skill",
            ] = to_skill

athlete_routine_cross

,Athlete,Level,Event,Event Routine,Default Skill to Upgrade,Default Upgrade Skill,Custom Skill to Upgrade,Custom Upgrade Skill
0,Kristy,XS,Beam,0,D1,D2,None,None
1,Kristy,XS,Beam,1,A1,A2,None,None
2,Kristy,XS,Bars,0,D1,D2,D2,D1
3,Kristy,XS,Bars,1,C1,C2,None,None
0,Autumn,XB,Beam,0,D1,D2,None,None
1,Autumn,XB,Beam,1,J1,J2,None,None
2,Autumn,XB,Beam,2,D2,D3,None,None
3,Autumn,XB,Beam,3,D3,D4,None,None
4,Autumn,XB,Beam,4,A1,A2,None,None
5,Autumn,XB,Bars,0,D1,D2,None,None
6,Autumn,XB,Bars,1,D2,D3,None,None

In [248]:
athlete_routine_cross["Skill to Upgrade"] = athlete_routine_cross.apply(
    lambda row: (
        row["Custom Skill to Upgrade"]
        if row["Custom Skill to Upgrade"] is not None
        else row["Default Skill to Upgrade"]
    ),
    axis=1,
)
athlete_routine_cross["Upgrade Skill"] = athlete_routine_cross.apply(
    lambda row: (
        row["Custom Upgrade Skill"]
        if row["Custom Upgrade Skill"] is not None
        else row["Default Upgrade Skill"]
    ),
    axis=1,
)
athlete_routine_cross

,Athlete,Level,Event,Event Routine,Default Skill to Upgrade,Default Upgrade Skill,Custom Skill to Upgrade,Custom Upgrade Skill,Skill to Upgrade,Upgrade Skill
0,Kristy,XS,Beam,0,D1,D2,None,None,D1,D2
1,Kristy,XS,Beam,1,A1,A2,None,None,A1,A2
2,Kristy,XS,Bars,0,D1,D2,D2,D1,D2,D1
3,Kristy,XS,Bars,1,C1,C2,None,None,C1,C2
0,Autumn,XB,Beam,0,D1,D2,None,None,D1,D2
1,Autumn,XB,Beam,1,J1,J2,None,None,J1,J2
2,Autumn,XB,Beam,2,D2,D3,None,None,D2,D3
3,Autumn,XB,Beam,3,D3,D4,None,None,D3,D4
4,Autumn,XB,Beam,4,A1,A2,None,None,A1,A2
5,Autumn,XB,Bars,0,D1,D2,None,None,D1,D2
6,Autumn,XB,Bars,1,D2,D3,None,None,D2,D3

In [250]:
augmented_routine_scores_long = routine_scores_long.merge(
    athlete_routine_cross[
        [
            "Athlete",
            "Level",
            "Event",
            "Event Routine",
            "Skill to Upgrade",
            "Upgrade Skill",
        ]
    ],
    how="left",
    on=["Athlete", "Level", "Event", "Event Routine"],
)
augmented_routine_scores_long

,Meet,Level,Athlete,Event,Event Score,Event Routine,Skill to Upgrade,Upgrade Skill
0,Meet 1,XB,Autumn,Beam,9.0,1,J1,J2
1,Meet 2,XB,Autumn,Beam,9.5,1,J1,J2
2,Meet 3,XB,Autumn,Beam,9.4,1,J1,J2
3,Meet 4,XB,Autumn,Beam,9.6,2,D2,D3
4,Meet 1,XS,Kristy,Beam,8.5,0,D1,D2
5,Meet 1,XB,Autumn,Bars,9.0,1,D2,D3
6,Meet 2,XB,Autumn,Bars,9.5,1,D2,D3
7,Meet 3,XB,Autumn,Bars,9.4,1,D2,D3
8,Meet 4,XB,Autumn,Bars,9.6,1,D2,D3
9,Meet 1,XS,Kristy,Bars,8.5,0,D2,D1

In [ ]:
def get_second_highest(x):
    y = np.sort(x)
    return y[-2] if len(y) > 1 else np.nan


# Create the new column using transform
augmented_routine_scores_long["Second Highest Score"] = (
    augmented_routine_scores_long.groupby(
        ["Level", "Athlete", "Event", "Event Routine"]
    )["Event Score"].transform(get_second_highest)
)
augmented_routine_scores_long

,Meet,Level,Athlete,Event,Event Score,Event Routine,Skill to Upgrade,Upgrade Skill,Second Highest Score
0,Meet 1,XB,Autumn,Beam,9.0,1,J1,J2,9.4
1,Meet 2,XB,Autumn,Beam,9.5,1,J1,J2,9.4
2,Meet 3,XB,Autumn,Beam,9.4,1,J1,J2,9.4
3,Meet 4,XB,Autumn,Beam,9.6,2,D2,D3,NaN
4,Meet 1,XS,Kristy,Beam,8.5,0,D1,D2,NaN
5,Meet 1,XB,Autumn,Bars,9.0,1,D2,D3,9.5
6,Meet 2,XB,Autumn,Bars,9.5,1,D2,D3,9.5
7,Meet 3,XB,Autumn,Bars,9.4,1,D2,D3,9.5
8,Meet 4,XB,Autumn,Bars,9.6,1,D2,D3,9.5
9,Meet 1,XS,Kristy,Bars,8.5,0,D2,D1,NaN

In [ ]:
filtered_routine_scores = augmented_routine_scores_long[
    (
        augmented_routine_scores_long["Event Score"]
        >= augmented_routine_scores_long["Second Highest Score"]
    )
    | augmented_routine_scores_long["Second Highest Score"].isna()
]
filtered_routine_scores = filtered_routine_scores.sort_values(
    ["Level", "Athlete", "Event", "Event Routine", "Meet"]
)
filtered_routine_scores

,Meet,Level,Athlete,Event,Event Score,Event Routine,Skill to Upgrade,Upgrade Skill,Second Highest Score
6,Meet 2,XB,Autumn,Bars,9.5,1,D2,D3,9.5
8,Meet 4,XB,Autumn,Bars,9.6,1,D2,D3,9.5
1,Meet 2,XB,Autumn,Beam,9.5,1,J1,J2,9.4
2,Meet 3,XB,Autumn,Beam,9.4,1,J1,J2,9.4
3,Meet 4,XB,Autumn,Beam,9.6,2,D2,D3,NaN
9,Meet 1,XS,Kristy,Bars,8.5,0,D2,D1,NaN
4,Meet 1,XS,Kristy,Beam,8.5,0,D1,D2,NaN

In [269]:
pivoted_routine_scores = filtered_routine_scores.groupby(
    ["Level", "Athlete", "Event", "Event Routine"], as_index=False
).agg(
    {
        "Meet": list,
        "Event Score": list,
        "Skill to Upgrade": "first",
        "Upgrade Skill": "first",
    }
)
pivoted_routine_scores

,Level,Athlete,Event,Event Routine,Meet,Event Score,Skill to Upgrade,Upgrade Skill
0,XB,Autumn,Bars,1,"[Meet 2, Meet 4]","[9.5, 9.6]",D2,D3
1,XB,Autumn,Beam,1,"[Meet 2, Meet 3]","[9.5, 9.4]",J1,J2
2,XB,Autumn,Beam,2,[Meet 4],[9.6],D2,D3
3,XS,Kristy,Bars,0,[Meet 1],[8.5],D2,D1
4,XS,Kristy,Beam,0,[Meet 1],[8.5],D1,D2

In [272]:
pivoted_routine_scores[["Meet #1", "Meet #2"]] = pd.DataFrame(
    pivoted_routine_scores["Meet"].tolist(), index=pivoted_routine_scores.index
)
pivoted_routine_scores[["Score #1", "Score #2"]] = pd.DataFrame(
    pivoted_routine_scores["Event Score"].tolist(), index=pivoted_routine_scores.index
)
pivoted_routine_scores.drop(columns=["Meet", "Event Score"], inplace=True)
pivoted_routine_scores

,Level,Athlete,Event,Event Routine,Skill to Upgrade,Upgrade Skill,Meet #1,Meet #2,Score #1,Score #2
0,XB,Autumn,Bars,1,D2,D3,Meet 2,Meet 4,9.5,9.6
1,XB,Autumn,Beam,1,J1,J2,Meet 2,Meet 3,9.5,9.4
2,XB,Autumn,Beam,2,D2,D3,Meet 4,None,9.6,NaN
3,XS,Kristy,Bars,0,D2,D1,Meet 1,None,8.5,NaN
4,XS,Kristy,Beam,0,D1,D2,Meet 1,None,8.5,NaN

In [278]:
pivoted_routine_scores["Active Routine"] = pivoted_routine_scores.groupby(
    ["Level", "Athlete", "Event"]
)["Event Routine"].transform("max")
pivoted_routine_scores["Baseline Routine"] = pivoted_routine_scores.groupby(
    ["Level", "Athlete", "Event"]
)["Event Routine"].transform("min")
pivoted_routine_scores["Is Active?"] = pivoted_routine_scores.apply(
    lambda row: "TRUE" if row["Event Routine"] == row["Active Routine"] else "FALSE",
    axis=1,
)
pivoted_routine_scores

,Level,Athlete,Event,Event Routine,Skill to Upgrade,Upgrade Skill,Meet #1,Meet #2,Score #1,Score #2,Active Routine,Is Active?,Baseline Routine
0,XB,Autumn,Bars,1,D2,D3,Meet 2,Meet 4,9.5,9.6,1,TRUE,1
1,XB,Autumn,Beam,1,J1,J2,Meet 2,Meet 3,9.5,9.4,2,FALSE,1
2,XB,Autumn,Beam,2,D2,D3,Meet 4,None,9.6,NaN,2,TRUE,1
3,XS,Kristy,Bars,0,D2,D1,Meet 1,None,8.5,NaN,0,TRUE,0
4,XS,Kristy,Beam,0,D1,D2,Meet 1,None,8.5,NaN,0,TRUE,0

In [285]:
skill_eval_df = pd.DataFrame(
    {
        "Period": [1, 2, 1, 1],
        "Event": ["Beam", "Beam", "Bars", "Bars"],
        "Athlete": ["Autumn"] * 3 + ["Kristy"],
        "Score": [2, 3, 4, 3],
        "Skill ID": ["J2", "J2", "D3", "D1"],
        "Level": ["XB"] * 3 + ["XS"],
    }
)


augmented_skill_eval_df = skill_eval_df.groupby(
    ["Level", "Athlete", "Event", "Skill ID"], as_index=False
).agg({"Score": "max"})
augmented_skill_eval_df = augmented_skill_eval_df.rename(
    columns={"Skill ID": "Upgrade Skill", "Score": "Upgrade Skill Score"}
)
augmented_skill_eval_df

  Level Athlete Event Upgrade Skill  Upgrade Skill Score
0    XB  Autumn  Bars            D3                    4
1    XB  Autumn  Beam            J2                    3
2    XS  Kristy  Bars            D1                    3

In [322]:
routine_and_skills_scores = pivoted_routine_scores.merge(
    augmented_skill_eval_df,
    on=["Level", "Athlete", "Event", "Upgrade Skill"],
    how="left",
)
routine_and_skills_scores["Ready to Upgrade?"] = routine_and_skills_scores.apply(
    lambda row: (
        "TRUE"
        if all(
            [
                not pd.isna(row["Score #1"]),
                not pd.isna(row["Score #2"]),
                not pd.isna(row["Upgrade Skill Score"]),
                row["Score #1"] >= 9.4,
                row["Score #2"] >= 9.4,
                row["Upgrade Skill Score"] >= 4,
            ]
        )
        else "FALSE"
    ),
    axis=1,
)
routine_and_skills_scores

,Level,Athlete,Event,Event Routine,Skill to Upgrade,Upgrade Skill,Meet #1,Meet #2,Score #1,Score #2,Active Routine,Is Active?,Baseline Routine,Upgrade Skill Score,Ready to Upgrade?
0,XB,Autumn,Bars,1,D2,D3,Meet 2,Meet 4,9.5,9.6,1,TRUE,1,4.0,TRUE
1,XB,Autumn,Beam,1,J1,J2,Meet 2,Meet 3,9.5,9.4,2,FALSE,1,3.0,FALSE
2,XB,Autumn,Beam,2,D2,D3,Meet 4,None,9.6,NaN,2,TRUE,1,NaN,FALSE
3,XS,Kristy,Bars,0,D2,D1,Meet 1,None,8.5,NaN,0,TRUE,0,3.0,FALSE
4,XS,Kristy,Beam,0,D1,D2,Meet 1,None,8.5,NaN,0,TRUE,0,NaN,FALSE

In [323]:
import itertools


def upgrade_status(row):
    if all([row["Is Active?"] == "TRUE", row["Ready to Upgrade?"] == "TRUE"]):
        return "pending"

    statuses = []
    if pd.isna(row["Score #1"]):
        statuses.append("missing routine score")
    elif row["Score #1"] < 9.4:
        statuses.append("insufficient routine score")
    if pd.isna(row["Score #2"]):
        statuses.append("missing routine score")
    elif row["Score #2"] < 9.4:
        statuses.append("insufficient routine score")
    if pd.isna(row["Upgrade Skill Score"]):
        statuses.append("missing skill score")
    elif row["Upgrade Skill Score"] < 4:
        statuses.append("insufficient skill score")
    statuses.sort()
    status_summaries = []
    for key, group in itertools.groupby(statuses):
        if key.endswith("skill score"):
            status_summaries.append(key)
        else:
            if key.startswith("missing"):
                n = len(list(group))
                s = "" if n == 1 else "s"
                status_summaries.append(f"{n} missing {key[8:]}{s}")
            if key.startswith("insufficient"):
                n = len(list(group))
                s = "" if n == 1 else "s"
                status_summaries.append(f"{n} insufficient {key[13:]}{s}")
    status_summaries.sort()
    return "; ".join(status_summaries)


routine_and_skills_scores["Upgrade Status"] = routine_and_skills_scores.apply(
    upgrade_status, axis=1
)
routine_and_skills_scores

,Level,Athlete,Event,Event Routine,Skill to Upgrade,Upgrade Skill,Meet #1,Meet #2,Score #1,Score #2,Active Routine,Is Active?,Baseline Routine,Upgrade Skill Score,Ready to Upgrade?,Upgrade Status
0,XB,Autumn,Bars,1,D2,D3,Meet 2,Meet 4,9.5,9.6,1,TRUE,1,4.0,TRUE,pending
1,XB,Autumn,Beam,1,J1,J2,Meet 2,Meet 3,9.5,9.4,2,FALSE,1,3.0,FALSE,insufficient skill score
2,XB,Autumn,Beam,2,D2,D3,Meet 4,None,9.6,NaN,2,TRUE,1,NaN,FALSE,1 missing routine score; missing skill score
3,XS,Kristy,Bars,0,D2,D1,Meet 1,None,8.5,NaN,0,TRUE,0,3.0,FALSE,1 insufficient routine score; 1 missing routin...
4,XS,Kristy,Beam,0,D1,D2,Meet 1,None,8.5,NaN,0,TRUE,0,NaN,FALSE,1 insufficient routine score; 1 missing routin...

In [324]:
routine_and_skills_scores["Admin Notes"] = ""
routine_and_skills_scores.loc[
    (routine_and_skills_scores["Is Active?"] == "FALSE")
    & (routine_and_skills_scores["Ready to Upgrade?"] == "FALSE"),
    "Admin Notes",
] = "Routine was upgraded without meeting upgrade requirements. Confirm that routine and skill scores are up to date."
routine_and_skills_scores

,Level,Athlete,Event,Event Routine,Skill to Upgrade,Upgrade Skill,Meet #1,Meet #2,Score #1,Score #2,Active Routine,Is Active?,Baseline Routine,Upgrade Skill Score,Ready to Upgrade?,Upgrade Status,Admin Notes
0,XB,Autumn,Bars,1,D2,D3,Meet 2,Meet 4,9.5,9.6,1,TRUE,1,4.0,TRUE,pending,
1,XB,Autumn,Beam,1,J1,J2,Meet 2,Meet 3,9.5,9.4,2,FALSE,1,3.0,FALSE,insufficient skill score,Routine was upgraded without meeting upgrade r...
2,XB,Autumn,Beam,2,D2,D3,Meet 4,None,9.6,NaN,2,TRUE,1,NaN,FALSE,1 missing routine score; missing skill score,
3,XS,Kristy,Bars,0,D2,D1,Meet 1,None,8.5,NaN,0,TRUE,0,3.0,FALSE,1 insufficient routine score; 1 missing routin...,
4,XS,Kristy,Beam,0,D1,D2,Meet 1,None,8.5,NaN,0,TRUE,0,NaN,FALSE,1 insufficient routine score; 1 missing routin...,

In [ ]:
statuses = [
    "missing routine score",
    "insufficient routine score",
    "insufficient skill score",
]
statuses.sort()  # The list must be sorted first: [1, 1, 1, 2, 2, 3, 4, 4]

# Group consecutive elements with the same key
new_res = []
for key, group in itertools.groupby(statuses):
    if key.endswith("skill score"):
        new_res.append(key)
    else:
        if key.startswith("missing"):
            n = len(list(group))
            s = "" if n == 1 else "s"
            new_res.append(f"{n} missing {key[8:]}{s}")
        if key.startswith("insufficient"):
            n = len(list(group))
            s = "" if n == 1 else "s"
            new_res.append(f"{n} insufficient {key[13:]}{s}")
sorted(new_res)

['1 insufficient routine score',
 '1 missing routine score',
 'insufficient skill score']

In [ ]:
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
pd.isna(df[(df["A"] == 11) | (df["A"] == 21)]["B"].max())

True

In [3]:
import matplotlib.colors as mcolors
import plotly.graph_objects as go
import pandas as pd

VERY_BAD_COLOR = "#f04f0a"
BAD_COLOR = "#e89e1e"
OK_COLOR = "#abb53f"
GOOD_COLOR = "#208c6f"

THRESHOLD = 90
DANGER_THRESHOLD = 80


def minmax_scaler(x, from_range=None, to_range=None, trim=False):
    """Scales a numpy array to the range [a, b] using min-max normalization.
    Ref: https://en.wikipedia.org/wiki/Feature_scaling#Rescaling_(min-max_normalization)
    """
    _min = np.nanmin(x)
    _max = np.nanmax(x)
    from_range = from_range or (_min, _max)
    to_range = to_range or (_min, _max)

    if from_range[0] == from_range[1]:
        raise ValueError(f"Values in `from_range` must be different. Got {from_range}")

    _is_arr = True
    try:
        len(x)
    except TypeError:
        _is_arr = False

    if _is_arr:
        return [_minmax_scaler(i, from_range, to_range, trim) for i in x]
    else:
        return _minmax_scaler(x, from_range, to_range, trim)


def _minmax_scaler(x, from_range, to_range, trim):
    """Scale a number from a given range to a new range using min-max normalization.
    Ref: https://en.wikipedia.org/wiki/Feature_scaling#Rescaling_(min-max_normalization)
    """
    old_low, old_high = from_range
    new_low, new_high = to_range
    if trim:
        if x < old_low:
            x = old_low
        elif x > old_high:
            x = old_high
    return new_low + (((x - old_low) * (new_high - new_low)) / (old_high - old_low))


def rgb_arr(n, very_bad_coef=3, logspace_base=10):
    """
    Usage Note
    ----------
    Increase `very_bad_coef` and/or `logspace_base` to increase the
    proportion of "bad" colors.
    """
    cmap = mcolors.LinearSegmentedColormap.from_list(
        "custom_linear_cmap",
        [VERY_BAD_COLOR] * very_bad_coef + [BAD_COLOR] + [OK_COLOR] + [GOOD_COLOR],
        N=n,
    )
    values = [
        cmap(i)[:3]
        for i in minmax_scaler(
            np.logspace(0, 1, n, base=logspace_base), to_range=(0, 1)
        )
    ]
    return [f"rgb({int(r * 255)},{int(g * 255)},{int(b * 255)})" for r, g, b in values]

In [4]:
_n = 100
data = (
    [i / _n for i in range(_n)] + [1, np.nan, 1] + [i / _n for i in range(_n)][::-1]
)  # [0, 0.2, 0.5, np.nan, 0.8, 1, 0.8, 0.8, np.nan, 0.1, 0, 1]
dt = list(range(len(data)))

dff = pd.DataFrame({"Date": dt, "Overall Behavior Score": data})
scale_factor = 100  # scale to 100 to report percentages
sample_size = len(dff)
dff = dff.sort_values(by="Date").reset_index(drop=True)
dff["Behavior Score (%)"] = dff["Overall Behavior Score"] * scale_factor
rgb_indices = (
    dff["Overall Behavior Score"]
    .fillna(0)
    .apply(minmax_scaler, from_range=(0, 1), to_range=(0, sample_size - 1), trim=True)
).astype(int)
rgb = rgb_arr(
    n=sample_size, very_bad_coef=5, logspace_base=20
)  # rgb_arr(n=sample_size)
bar_color = [rgb[i] for i in rgb_indices]
dff["rgb_indices"] = rgb_indices
dff["bar_color"] = bar_color
student_mean = dff["Behavior Score (%)"].mean()
dff[["Behavior Score (%)", "rgb_indices", "bar_color"]].head(10)

   Behavior Score (%)  rgb_indices       bar_color
0                 0.0            0  rgb(240,79,10)
1                 1.0            2  rgb(240,79,10)
2                 2.0            4  rgb(240,79,10)
3                 3.0            6  rgb(240,79,10)
4                 4.0            8  rgb(240,79,10)
5                 5.0           10  rgb(240,79,10)
6                 6.0           12  rgb(240,79,10)
7                 7.0           14  rgb(240,79,10)
8                 8.0           16  rgb(240,79,10)
9                 9.0           18  rgb(240,79,10)

In [5]:
fig = go.Figure()
x_data = list(range(sample_size))
fig.add_trace(
    go.Bar(
        x=dff["Date"],
        y=dff["Behavior Score (%)"],
        marker={"color": dff["bar_color"]},
        showlegend=False,
    )
)
fig.add_shape(
    type="line",
    xref="paper",
    yref="y",
    x0=0,
    y0=THRESHOLD,
    x1=1,
    y1=THRESHOLD,
    line=dict(
        color="black",
        width=2,
        dash="dot",
    ),
    name=f"Class Expectation ({THRESHOLD:.0f}%)",
)
fig.add_trace(
    go.Scatter(
        x=dff["Date"],
        y=[student_mean] * dff.shape[0],
        mode="lines",
        line=dict(
            color="black" if student_mean >= THRESHOLD else "#f04f0a",
            width=2,
        ),
        name=f"Average Score ({student_mean:.2f}%)",
    )
)
fig.update_layout(
    height=400,
    title={
        "text": "Class Behavior",
    },
    xaxis_title="Class Day",
    yaxis_title="Score (%)",
    xaxis={"showgrid": False, "showticklabels": False},
    yaxis_range=[-5, 105],
    yaxis={"showgrid": False, "showticklabels": True},
    bargap=0,
    bargroupgap=0,
)

fig.show()

In [ ]:
from datetime import datetime, timedelta

today = datetime.now()

date_list = sorted(
    list(set([(today - timedelta(days=i)).replace(day=1).date() for i in range(400)]))
)
formatted_date_list = [i.strftime("%b-%y") for i in date_list]
formatted_date_list

['Nov-24',
 'Dec-24',
 'Jan-25',
 'Feb-25',
 'Mar-25',
 'Apr-25',
 'May-25',
 'Jun-25',
 'Jul-25',
 'Aug-25',
 'Sep-25',
 'Oct-25',
 'Nov-25',
 'Dec-25']

In [19]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8]
a[-3:]

[6, 7, 8]

In [20]:
dict(zip(date_list, formatted_date_list))

{datetime.date(2024, 11, 1): 'Nov-24',
 datetime.date(2024, 12, 1): 'Dec-24',
 datetime.date(2025, 1, 1): 'Jan-25',
 datetime.date(2025, 2, 1): 'Feb-25',
 datetime.date(2025, 3, 1): 'Mar-25',
 datetime.date(2025, 4, 1): 'Apr-25',
 datetime.date(2025, 5, 1): 'May-25',
 datetime.date(2025, 6, 1): 'Jun-25',
 datetime.date(2025, 7, 1): 'Jul-25',
 datetime.date(2025, 8, 1): 'Aug-25',
 datetime.date(2025, 9, 1): 'Sep-25',
 datetime.date(2025, 10, 1): 'Oct-25',
 datetime.date(2025, 11, 1): 'Nov-25',
 datetime.date(2025, 12, 1): 'Dec-25'}